# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalendarMemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalendarMem

  pod 'FSCalendar'

  target 'CalendarMemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalendarMemoUITests' do
    # Pods for testing
  end

end
